---
name: "reconst_fodf"
description: Perform FODF reconstruction from a dwi volume for a selected number of shells. 
  Note that multiple choices of reconstruction method are available throught the method argument. 
  The single-shell single-tissue (ssst) method can be performed by selecting only one shell and choosing ssst_fodf.
  The multi-shell single-tissue (msst) method (default) can be performed by selecting multiple shells and choosing ssst_fodf.
  The multi-shell multi-tissue (msmt) method can be performed by selecting multiple shells and choosing msmt_fodf.
keywords:
  - FODF
  - Local Model
tools:
  - "Scilpy":
      description: "The Sherbrooke Connectivity Imaging Lab (SCIL) Python dMRI processing toolbox."
      homepage: "https://github.com/scilus/scilpy.git"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`

  - dwi:
      type: file
      description: Nifti DWI volume to reconstruct FODF from.
      pattern: "*.{nii,nii.gz}"

  - bval:
      type: file
      description: B-values in FSL format.
      pattern: "*.bval"

  - bvec:
      type: file
      description: B-vectors in FSL format.
      pattern: "*.bvec"

  - mask:
      type: file
      description: B0 mask.
      pattern: "*.{nii,nii.gz}"

  - frf:
      type: file or list
      description: Fiber Response Function (FRF). In the case of msmt_fodf method,
        should be a list of files containing the wm_frf, gm_frf and csf_frf, in that order.
      pattern: "*.txt"

  - method:
      type: string
      description: Reconstruction method. Either ssst_fodf or msmt_fodf. This choice 
        changes the frf input and all the output, be careful.
      pattern: "*_fodf"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`

  - fodf:
      type: file
      description: FODF map.
      pattern: "*fodf.nii.gz"

  - wm_fodf:
      type: file
      description: WM FODF map.
      pattern: "*wm_fodf.nii.gz"

  - gm_fodf:
      type: file
      description: GM FODF map.
      pattern: "*gm_fodf.nii.gz"

  - csf_fodf:
      type: file
      description: CSF FODF map.
      pattern: "*csf_fodf.nii.gz"

  - vf:
      type: file
      description: Volume fraction map.
      pattern: "*vf.nii.gz"

  - vf_rgb:
      type: file
      description: Volume fraction map in rgb.
      pattern: "*vf_rgb.nii.gz"

  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@gagnonanthony"
  - "@karanphil"
