---
name: "registration_tractogram"
description: Apply transform to bundles centroid
keywords:
  - tractography
  - registration
  - bundles
tools:
  - "scilpy":
      description: "The Sherbrooke Connectivity Imaging Lab (SCIL) Python dMRI processing toolbox."
      homepage: "https://github.com/scilus/scilpy.git"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`

  - anat:
      type: file
      description: FA nifti format as anatomical image
      pattern: "*.{nii,nii.gz}"

  - transfo:
      type: file
      description: ANTs affine transform
      pattern: "*.{txt,npy,mat}"

  - centroid_dir:
      type: directory
      description: Path to directory containing
      pattern: "*.{trk,trk}"


output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`

  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

  - bundle:
      type: file
      description: Warped bundle to atlas
      pattern: "*.{trk}"

authors:
  - "@scilus"
