---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "segmentation_freesurferseg"
channels:
  - Docker
  - Apptainer
dependencies:
  - "MRtrix"
  - "scilpy"
