---
name: "registration_bundleregistration"
description: Apply transform to bundles centroid
keywords:
  - Diffusion MRI
  - Registration
  - Bundles
  - Tractogram
tools:
  - "scilpy":
      description: "The Sherbrooke Connectivity Imaging Lab (SCIL) Python dMRI processing toolbox."
      homepage: "https://github.com/scilus/scilpy.git"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`

  - anat:
      type: file
      description: FA nifti format as anatomical image
      pattern: "*.{nii,nii.gz}"

  - transfo:
      type: file
      description: ANTs affine transform
      pattern: "*.mat"

  - centroid_dir:
      type: directory
      description: Path to directory containing
      pattern: "*.trk"


output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`

  - bundle:
      type: file
      description: Warped bundle to atlas
      pattern: "*.trk"

  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@scilus"
