name: Assign PR reviewers

on:
  pull_request:
    types: [opened, ready_for_review, reopened]

jobs:
  assign-reviewers:
    name: Assign reviewers
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    if: ${{ github.repository == 'scilus/nf-scil' }}
    steps:
      - name: Get review assignment token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.REVIEW_APP_ID }}
          private-key: ${{ secrets.REVIEW_APP_KEY }}

      - uses: necojackarc/auto-request-review@v0.13.0
        with:
          config: .github/reviewers.yml
          token: ${{ steps.generate-token.outputs.token }}
